### ISSUE TITLE
Demo can't launch on iPhone and simulator.

### ISSUE THREAD

**Issue by lennondong** [meiwin/NgKeyboardTracker#4]
Tried many times. Demo can't launch at all.

**Comment by meiwin** [comment]
is there any error?

also, please make sure you choose the correct target to launch: `NgKeyboardTrackerDemo`.

<img width="492" alt="screen shot 2015-09-23 at 10 57 46 am" src="https://cloud.githubusercontent.com/assets/136135/10036987/fbb8405e-61e1-11e5-8f4b-9e737705cb6a.png">

**Comment by lennondong** [comment]
Thanks for your reply. You're right. I didn't choose the correct target.

**Comment by meiwin** [comment]
:ok:
